spoonacular:
  key: 'ENTER_KEY_HERE'
  host: spoonacular-recipe-food-nutrition-v1.p.mashape.com

feign:
  client:
    config:
      spoonacular:
        url: "https://${spoonacular.host}/"
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder

cloud:
  aws:
    bucket: 'taco-resources'
    region:
      static: us-east-1
    credentials:
      accessKey: 'ENTER_ACCESS_KEY_HERE'
      secretKey: 'ENTER_SECRET_KEY_HERE'
      instanceProfile: true